#! /usr/bin/env python
# encoding: utf-8

bld(features='cxx cxxshlib',
    source=bld.path.ant_glob('*.cpp'),
    target='petro_android',
    export_includes=['jni'],
    install_path=None,
    lib=['android'],
    use=['petro'])
