#! /usr/bin/env python
# encoding: utf-8

bld(features='cxx cxxshlib copy_binary',
    source=bld.path.ant_glob('*.cpp'),
    target='petro_android',
    export_includes=['jni'],
    install_path=None,
    copy_path='../app/src/main/jniLibs/armeabi',
    lib=['android'],
    use=['petro'])
